"""`gen/HE Sector Leads.md`: the generated view of the HE sector assignments.

Source of record is the table on the Fin page `Signal Strength Stocks` (see
`spine/assignments.py`). This page is embedded there and on `HE-Sectors`; nobody edits
it, and it must never be mistaken for the source — the banner says so.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Any

from . import paths
from .assignments import Assignment, current


def render(parsed: dict[str, Any], on: str | None = None) -> str:
    on = on or date.today().isoformat()
    asg: list[Assignment] = parsed["assignments"]
    now = current(asg, on)
    lines = [
        "---",
        "type: generated",
        "generator: hedgeye.spine render (render_leads)",
        f"rendered: {datetime.now().isoformat(timespec='minutes')}",
        "---",
        "> [!info] Machine-owned view — regenerated by `spine render`. **Do not edit.** "
        "The source is the assignments table on [[Signal Strength Stocks]]; change it there.",
        "",
        f"### Leads in force on {on}",
        "",
        "| HE sector | Lead | Stand-in | Since | Note |",
        "|---|---|---|---|---|",
    ]
    by_sector: dict[str, list[Assignment]] = {}
    for a in now:
        by_sector.setdefault(a.sector, []).append(a)
    for sector in sorted(by_sector, key=str.lower):
        rows = by_sector[sector]
        lead = next((a for a in rows if a.role == "lead"), None)
        standins = [a for a in rows if a.role == "stand-in"]
        lead_txt = f"[[{lead.analyst}]]" if lead else "**none**"
        si_txt = ", ".join(f"[[{a.analyst}]]" for a in standins) or ""
        since = lead.start if lead else (standins[0].start if standins else "")
        note = lead.note if lead else (standins[0].note if standins else "")
        lines.append(f"| {sector} | {lead_txt} | {si_txt} | {since} | {note} |")
    # per analyst
    per: dict[str, list[str]] = {}
    for a in now:
        per.setdefault(a.analyst, []).append(
            a.sector + (" (stand-in)" if a.role == "stand-in" else "")
        )
    lines += ["", "### By analyst", ""]
    for analyst in sorted(per, key=str.lower):
        lines.append(f"- [[{analyst}]] — " + " · ".join(per[analyst]))
    ended = sorted((a for a in asg if a.end and a.end < on), key=lambda a: a.end or "")
    if ended:
        lines += ["", "### Ended", ""]
        for a in ended:
            lines.append(
                f"- {a.sector} — [[{a.analyst}]] {a.start} → {a.end} {a.note}".rstrip()
            )
    if parsed["aliases"]:
        lines += ["", "### Sector name aliases in the data", "",
                  "| Printed | Canonical | From | Until |", "|---|---|---|---|"]  # fmt: skip
        for al in parsed["aliases"]:
            lines.append(
                f"| {al.printed} | {al.canonical} | {al.start} | {al.end or ''} |"
            )
    if parsed["problems"]:
        lines += ["", "> [!warning] Source table problems", ""]
        lines += [f"> - {p}" for p in parsed["problems"]]
    return "\n".join(lines) + "\n"


def write(text: str) -> str:
    paths.GEN_DIR.mkdir(parents=True, exist_ok=True)
    out = paths.GEN_DIR / "HE Sector Leads.md"
    out.write_text(text)
    return str(out)
