"""`render`: machine-owned Obsidian page under Fin/Areas/Hedgeye/gen/ (decision §4-7).

Randy embeds it with `![[SS Stocks]]`; nothing else writes to gen/, and this never
writes anywhere else.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from . import paths


def _rank_sort_key(r: dict[str, Any]) -> tuple[int, float]:
    kind = r.get("rank_kind")
    rank = r.get("best_idea_rank") or ""
    if kind == "ranked":
        try:
            n, m = rank.split("/")
            return (0, int(n) / max(int(m), 1))
        except ValueError:
            return (0, 9.0)
    return ({"bench": 2, "km-signal": 1}.get(kind, 3), 0.0)


def render_ss_page(
    latest: dict[str, Any],
    diff: dict[str, Any] | None,
    holdings_cmp: dict[str, Any] | None,
    holdings_meta: dict[str, Any] | None,
    status: dict[str, Any],
) -> str:
    L: list[str] = []
    L.append("---\ntype: generated\ngenerator: hedgeye.spine render\n"
             f"rendered: {datetime.now().isoformat(timespec='minutes')}\n---\n")  # fmt: skip
    L.append("> [!info] Machine-owned page — regenerated by `spine render`. "
             "Do not edit; embed with `![[SS Stocks]]`.\n")  # fmt: skip
    sp = latest["subject_parsed"]
    ck = latest.get("checks") or {}
    L.append(f"## Signal Strength Stocks — {latest.get('published_at', '?')}\n")
    L.append(f"**{sp.get('count')} stocks** · subject: {latest['subject']} · "
             f"checks {ck.get('passed', '?')}/{ck.get('applicable', '?')} "
             f"({'all pass' if ck.get('all_pass') else 'FAILURES — see below'}) · "
             f"feed_item `{latest['feed_item_id']}`\n")  # fmt: skip
    if ck and not ck.get("all_pass"):
        for k, v in ck.get("results", {}).items():
            if not v.get("pass"):
                L.append(f"- ⚠️ `{k}`: {v}\n")

    if diff:
        L.append(f"\n### Changes since {diff['from']['published_at']}\n")
        L.append(f"- Added: {', '.join(r['ticker'] for r in diff['added']) or '—'}\n")
        L.append(
            f"- Removed: {', '.join(r['ticker'] for r in diff['removed']) or '—'}\n"
        )
        fc = [
            c
            for c in diff["stable_field_changes"]
            if c.get("significance") not in ("denominator", "rounding")
        ]
        noise = len(diff["stable_field_changes"]) - len(fc)
        L.append(
            f"- Stable-field changes: {len(fc)}"
            + (f" (+{noise} denominator/rounding-only, not shown)" if noise else "")
            + "\n"
        )
        for c in fc:
            L.append(
                f"  - **{c['ticker']}** {c['field']}: `{c['from']}` → `{c['to']}` "
                f"({c.get('significance')})\n"
            )

    if holdings_cmp:
        L.append("\n### Holdings vs Signal Strength\n")
        if holdings_meta:
            L.append(f"_Fidelity: {holdings_meta.get('fidelity')} · "
                     f"IBKR: {holdings_meta.get('ibkr') or 'none'}_\n\n")  # fmt: skip
        for title, key in (
            ("Held and ranked (Best Idea list)", "held_in_ss_ranked"),
            ("Held, on the Bench", "held_in_ss_bench"),
            ("Held, KM Signal only", "held_in_ss_km_signal"),
        ):
            rows = holdings_cmp[key]
            L.append(f"**{title}** ({len(rows)})\n\n")
            if rows:
                L.append(
                    "| Ticker | Rank | Analyst | Sector | Days on | Value |\n|---|---|---|---|---:|---:|\n"
                )
                for r in sorted(rows, key=_rank_sort_key):
                    L.append(f"| {r['ticker']} | {r['best_idea_rank']} | {r['analyst']} | "
                             f"{r['sector']} | {r['days_on']} | {r['value']:,.0f} |\n")  # fmt: skip
            L.append("\n")
        ns = holdings_cmp["held_stocks_not_in_ss"]
        L.append(f"**Held stocks not in Signal Strength** ({len(ns)}): "
                 + (", ".join(r["ticker"] for r in ns) or "—") + "\n\n")  # fmt: skip
        nh = holdings_cmp["ss_not_held"]
        L.append(f"**In Signal Strength, not held** ({len(nh)}): "
                 + (", ".join(f"{r['ticker']} ({r['best_idea_rank']})" for r in nh) or "—")
                 + "\n\n")  # fmt: skip
        un = holdings_cmp["unclassified"]
        if un:
            L.append(f"**Unclassified holdings** ({len(un)}): "
                     + ", ".join(h["ticker"] for h in un) + "\n\n")  # fmt: skip

    L.append("\n### Current roster\n\n")
    L.append("| Days | Ticker | Signal | Entry | Recent | % | Sector | Analyst | Rank |\n"
             "|---:|---|---|---:|---:|---:|---|---|---|\n")  # fmt: skip
    for r in latest["roster"]["rows"]:
        pct = r.get("pct_since_signal")
        L.append(f"| {r.get('days_on')} | **{r['ticker']}** | {r.get('signal_date')} | "
                 f"{r.get('entry_price')} | {r.get('recent_price')} | "
                 f"{'' if pct is None else f'{pct:+.1f}'} | {r.get('sector')} | "
                 f"{r.get('analyst')} | {r.get('best_idea_rank')} |\n")  # fmt: skip

    L.append("\n### Pipeline status\n\n")
    for k, v in status.items():
        L.append(f"- {k}: {v}\n")
    return "".join(L)


def write_ss_page(text: str) -> str:
    paths.GEN_DIR.mkdir(parents=True, exist_ok=True)
    out = paths.GEN_DIR / "SS Stocks.md"
    out.write_text(text)
    return str(out)
