"""`render-etf`: machine-owned page `Fin/Areas/Hedgeye/gen/ETF Books.md` + the S31 report.

S31 (scenarios.md): are the PS and ETF Pro long books the same set, and with what lag?
Answered per month, never pooled alone (§0): equal at PS time · equal by end of day ·
disagreed, and how many days a disagreement took to clear.
"""

from __future__ import annotations

from collections import defaultdict
from datetime import datetime
from typing import Any

from .aliases import canon
from .etf_checks import ep_anchors, ep_state_at, ps_tickers
from .holdings import Holding


def s31_report(ps: list[dict[str, Any]]) -> dict[str, Any]:
    by_month: dict[str, dict[str, Any]] = defaultdict(lambda: {"days": 0, "equal_at_ps_time": 0, "equal_by_eod": 0, "disagree": 0, "no_anchor": 0, "resolved_days": []})  # fmt: skip
    disagreements = []
    for s in ps:
        r = (s.get("checks") or {}).get("ps_vs_ep_long")
        if not r:
            continue
        m = (s.get("published_at") or "")[:7]
        b = by_month[m]
        b["days"] += 1
        if r.get("pass") is None:
            b["no_anchor"] += 1
        elif r["equal_at_ps_time"]:
            b["equal_at_ps_time"] += 1
        elif r["equal_by_end_of_day"]:
            b["equal_by_eod"] += 1
        else:
            b["disagree"] += 1
            b["resolved_days"].append(r.get("resolved_after_days"))
            disagreements.append(
                {
                    "date": s["published_at"][:10],
                    "only_ps": r["only_ps_eod"],
                    "only_ep": r["only_ep_eod"],
                    "resolved_after_days": r.get("resolved_after_days"),
                }
            )
    months = []
    for m in sorted(by_month):
        b = by_month[m]
        comparable = b["days"] - b["no_anchor"]
        months.append({"month": m, "ps_reports": b["days"], "comparable": comparable,
                       "equal_at_ps_time": b["equal_at_ps_time"], "equal_by_eod": b["equal_by_eod"],
                       "disagree": b["disagree"],
                       "same_day_rate": round((b["equal_at_ps_time"] + b["equal_by_eod"]) / comparable, 3) if comparable else None,
                       "resolved_days": b["resolved_days"]})  # fmt: skip
    return {"months": months, "disagreements": disagreements}


def _fmt(v: Any) -> str:
    return "" if v is None else str(v)


def render(
    ps: list[dict[str, Any]], wk: list[dict[str, Any]], ch: list[dict[str, Any]],
    a10: list[dict[str, Any]], holdings: list[Holding] | None, meta: dict[str, Any] | None,
) -> tuple[str, dict[str, Any]]:  # fmt: skip
    L: list[str] = []
    L.append("---\ntype: generated\ngenerator: hedgeye.spine render-etf\n"
             f"rendered: {datetime.now().isoformat(timespec='minutes')}\n---\n")  # fmt: skip
    L.append("> [!info] Machine-owned page — regenerated by `spine render-etf`. "
             "Do not edit; embed with `![[ETF Books]]`.\n")  # fmt: skip
    latest_ps = next((s for s in reversed(ps) if s.get("roster")), None)
    anchors = ep_anchors(wk)
    ep_now = ep_state_at(datetime.now(), anchors, ch) if anchors else None
    latest_a10 = next((s for s in reversed(a10) if s.get("roster")), None)

    # --- today
    L.append("## The books today\n\n")
    if latest_ps:
        ck = latest_ps.get("checks") or {}
        r = ck.get("ps_vs_ep_long") or {}
        L.append(f"**Portfolio Solutions** {latest_ps['published_at']} · {len(ps_tickers(latest_ps))} ETFs + cash · "
                 f"PS = EP long: {'yes' if r.get('pass') else ('no' if r.get('pass') is False else 'n/a')}"
                 + (f" (only PS: {', '.join(r['only_ps_eod'])}; only EP: {', '.join(r['only_ep_eod'])})" if r.get('pass') is False else "") + "\n\n")  # fmt: skip
        if latest_ps.get("commentary"):
            L.append(f"> Keith: \"{latest_ps['commentary']}\"\n\n")
        L.append(
            "| Rank | Ticker | Entry | Asset class | Sizing | Wk Δ |\n|---:|---|---|---|---|---:|\n"
        )
        for row in latest_ps["roster"]:
            L.append(
                f"| {row['rank']} | **{row['ticker']}** | {_fmt(row.get('entry_date'))} | {_fmt(row.get('asset_class'))} | {_fmt(row.get('sizing'))} | {_fmt(row.get('week_change'))} |\n"
            )
        L.append("\n")
    if ep_now:
        L.append(
            f"**ETF Pro Plus** as of now (anchor {ep_now['anchor_at']} + {len(ep_now['changes_applied'])} change emails)\n\n"
        )
        L.append(
            f"- Long ({len(ep_now['long'])}): {', '.join(sorted(ep_now['long']))}\n"
        )
        L.append(
            f"- Short ({len(ep_now['short'])}): {', '.join(sorted(ep_now['short']))}\n\n"
        )
    if latest_a10:
        L.append(f"**Go-Anywhere 10** {latest_a10['published_at']}: "
                 + ", ".join(r["ticker"] for r in latest_a10["roster"]) + "\n\n")  # fmt: skip

    # --- holdings vs books
    if holdings is not None and latest_ps and ep_now:
        ps_set = ps_tickers(latest_ps)
        a10_set = {
            canon(r["ticker"], (latest_a10 or {}).get("published_at"))
            for r in (latest_a10 or {}).get("roster", [])
        }
        held = {h.ticker: h for h in holdings if h.asset_class in ("etf", "fund")}
        L.append("## Holdings vs the books\n\n")
        if meta:
            L.append(
                f"_Fidelity: {meta.get('fidelity')} · IBKR: {meta.get('ibkr') or 'none'}_\n\n"
            )
        in_ps = sorted(set(held) & ps_set)
        in_ep_short = sorted(set(held) & ep_now["short"])
        not_in_any = sorted(set(held) - ps_set - ep_now["long"] - a10_set)
        ps_not_held = sorted(ps_set - set(held))
        L.append(
            f"- Held ETFs in the PS/EP long book ({len(in_ps)}): {', '.join(in_ps) or '—'}\n"
        )
        L.append(
            f"- **Held ETFs that EP has SHORT** ({len(in_ep_short)}): {', '.join(in_ep_short) or '—'}\n"
        )
        L.append(
            f"- Held ETFs in none of the books ({len(not_in_any)}): {', '.join(not_in_any) or '—'}\n"
        )
        L.append(
            f"- In PS, not held ({len(ps_not_held)}): {', '.join(ps_not_held) or '—'}\n"
        )
        opts = [h for h in holdings if h.option]
        if opts:
            L.append(
                "\n**Options** (exposure to the underlying, checked against the EP books)\n\n"
            )
            L.append(
                "| Contract | Qty | Exposure | Underlying in EP |\n|---|---:|---|---|\n"
            )
            for h in sorted(opts, key=lambda x: x.option["underlying"]):
                o = h.option
                u = canon(o["underlying"])
                if o["exposure"] == "short":
                    where = (
                        "**SHORT book ✓**"
                        if u in ep_now["short"]
                        else (
                            "LONG book ⚠ (exposure conflicts)"
                            if u in ep_now["long"]
                            else "neither"
                        )
                    )
                else:
                    where = (
                        "**LONG book ✓**"
                        if u in ep_now["long"]
                        else (
                            "SHORT book ⚠ (exposure conflicts)"
                            if u in ep_now["short"]
                            else "neither"
                        )
                    )
                L.append(
                    f"| {u} {o['expiry']} {o['strike']:g} {o['put_call']} | {o['contracts']:g} "
                    f"| {o['exposure']} {u} | {where} |\n"
                )
        L.append("\n")

    # --- S31
    rep = s31_report(ps)
    L.append("## S31 — PS long book vs ETF Pro long book, by month\n\n")
    L.append(
        "| Month | PS reports | Comparable | Equal at PS time | Equal by EOD | Disagree | Same-day rate | Days to resolve |\n|---|---:|---:|---:|---:|---:|---:|---|\n"
    )
    for m in rep["months"]:
        L.append(
            f"| {m['month']} | {m['ps_reports']} | {m['comparable']} | {m['equal_at_ps_time']} | {m['equal_by_eod']} | {m['disagree']} | {_fmt(m['same_day_rate'])} | {', '.join(_fmt(x) for x in m['resolved_days'])} |\n"
        )
    L.append(
        "\n_Comparable = an EP weekly anchor exists within 45 days; before Sep-2025 the weekly issues were image-only._\n\n"
    )
    L.append(
        "### Disagreements\n\n| Date | Only in PS | Only in EP | Resolved after |\n|---|---|---|---:|\n"
    )
    for d in rep["disagreements"]:
        L.append(
            f"| {d['date']} | {', '.join(d['only_ps'])} | {', '.join(d['only_ep'])} | {_fmt(d['resolved_after_days'])} |\n"
        )

    # --- pipeline
    L.append("\n### Pipeline status\n\n")
    L.append(
        f"- PS reports: {len(ps)} (latest {ps[-1]['published_at'] if ps else '—'})\n"
    )
    L.append(
        f"- EP change emails: {len(ch)} (latest {ch[-1]['published_at'] if ch else '—'}) · weekly anchors: {len(anchors)} (latest {anchors[-1]['published_at'] if anchors else '—'})\n"
    )
    L.append(
        f"- Any10 reports: {len(a10)} (latest {a10[-1]['published_at'] if a10 else '—'})\n"
    )
    wk_fail = [
        s["published_at"][:10]
        for s in wk
        if (s.get("checks") or {}).get("ep_weekly_vs_replay", {}).get("pass") is False
    ]
    L.append(f"- EP weekly vs ledger failures: {', '.join(wk_fail) or 'none'}\n")
    return "".join(L), rep
